### ISSUE TITLE
Docker-Compose - Can't find interfaces

### ISSUE THREAD

**Issue by hellor00t** [uxbh/ztdns#16]
Error: `fatal msg="Could not get interface: route ip+net: no such network interface\n"`
interface = "zt7nnjn3xu" list in .ztdns.toml in the root directory of the git repo

I can start the service using the pre-compiled executable with the same config file and have no problems.

Running this on CentOS 7 as root.

**Comment by step21** [comment]
Same thing here...

**Comment by Kznzl** [comment]
It seems that the error is raised because by default the containerized daemon doesn't have access to any of the zerotier interfaces of the host machine. 

It's possible to solve the issue by commenting out the interface section in zerotier config, so the daemon is bound to all interfaces inside the container, and configure some port forwarding in compose file instead:
```
version: '3'
services:
  ztdns:
    build: .
    ports:
     - "192.168.191.218:5356:53/udp"
    volumes:
     - .ztdns.toml:/app/.ztdns.toml
```
